export type HeroFaction = "Warrior" | "Ranger" | "Warlock";
export type HeroRole = "Tank" | "Carry" | "Support";

export interface Hero {
  slug: string; name: string; rarity: "UR"; faction: HeroFaction; role: HeroRole;
  image: string; summary: string; unlock: string; skills: string[];
}

export const heroStats = { attack: "15,971", hp: "2,236,301", defense: "15,971", command: "350" } as const;

export const heroes: Hero[] = [
  { slug: "arthur", name: "Arthur", rarity: "UR", faction: "Warrior", role: "Tank", image: "/images/heroes/arthur.webp", summary: "A durable frontline defender who shields allies and controls the opening of a fight.", unlock: "Available early through the Tavern; the pool becomes less focused as the server ages.", skills: ["Battle Shield", "Earthshattering", "Rock Solid", "Strong Will", "Tenacity"] },
  { slug: "marlena", name: "Marlena", rarity: "UR", faction: "Warrior", role: "Carry", image: "/images/heroes/marlena.webp", summary: "A high-damage Warrior carry built to pressure priority targets and anchor an early squad.", unlock: "Available from the start through First Top Up, Top Up Bonus rewards, and Daily Offers.", skills: ["Skybreaker Slash", "Peerless Blade", "Crimson Bloom", "War God’s Will", "Tenacity"] },
  { slug: "nicole", name: "Nicole", rarity: "UR", faction: "Warlock", role: "Support", image: "/images/heroes/nicole.webp", summary: "A late-server Warlock support who strengthens allies with fire-themed utility.", unlock: "Introduced through the Hero Pass around server day 99.", skills: ["Ember Dust", "Inferno Array", "Heartwarming Flame", "Flame Soul Power", "Tenacity"] },
  { slug: "annie", name: "Annie", rarity: "UR", faction: "Warlock", role: "Carry", image: "/images/heroes/annie.webp", summary: "A candy-powered damage dealer whose kit rewards sustained offensive pressure.", unlock: "Introduced through the Hero Pass around server day 15 and later offered through Daily Offers.", skills: ["Candy", "Candy Jar", "Surprise Gift", "Charged Gummies", "Tenacity"] },
  { slug: "jester", name: "Jester", rarity: "UR", faction: "Warlock", role: "Carry", image: "/images/heroes/jester.webp", summary: "An unpredictable Warlock carry who turns card tricks into concentrated damage.", unlock: "Becomes available when a server is roughly two weeks old.", skills: ["Deal Cards", "Joker Ace", "Hearthunt Red Card", "Frenzied Emotion", "Tenacity"] },
  { slug: "red-lady", name: "Red Lady", rarity: "UR", faction: "Ranger", role: "Carry", image: "/images/heroes/red-lady.webp", summary: "A relentless Ranger carry centered on blades, blood effects, and finishing pressure.", unlock: "Introduced through Daily Offers around server day 36.", skills: ["Blood Blade", "Crimson Rose", "Bloodthirsty Slaughter", "Lone Flower", "Tenacity"] },
  { slug: "billy", name: "Billy", rarity: "UR", faction: "Warlock", role: "Tank", image: "/images/heroes/billy.webp", summary: "A puppet-themed Warlock tank who absorbs pressure and disrupts enemy plans.", unlock: "Becomes available around server day 85.", skills: ["Wooden Frame", "Truth and Lies", "Fate’s Thread", "Puppet", "Tenacity"] },
  { slug: "cynthia", name: "Cynthia", rarity: "UR", faction: "Ranger", role: "Carry", image: "/images/heroes/cynthia.webp", summary: "A moon-blade Ranger carry with strong early damage and long-term Tavern availability.", unlock: "Appears in Daily Offers during the first week and later joins the Tavern pool.", skills: ["Moon Blade", "Moonfall Dance", "Lunar Hunt", "Moon’s Blessing", "Tenacity"] },
  { slug: "zoya", name: "Zoya", rarity: "UR", faction: "Warrior", role: "Carry", image: "/images/heroes/zoya.webp", summary: "A mobile Warrior carry whose hunting kit is designed to punish exposed targets.", unlock: "Introduced through Daily Offers around server day 57.", skills: ["Dagger", "Forest Hunter", "Mountain God Wrath", "Lady of the Forest", "Tenacity"] },
  { slug: "bell", name: "Bell", rarity: "UR", faction: "Ranger", role: "Support", image: "/images/heroes/bell.webp", summary: "A musical Ranger support who combines healing, inspiration, and team-wide buffs.", unlock: "Introduced through Daily Offers around server day 71.", skills: ["Musical Note", "Inspiration", "Healing Sound", "Battle Anthem", "Tenacity"] },
  { slug: "harper", name: "Harper", rarity: "UR", faction: "Warrior", role: "Support", image: "/images/heroes/harper.webp", summary: "A protective Warrior support who uses bubbles and battle music to sustain a squad.", unlock: "Introduced through Daily Offers around server day 22.", skills: ["Bubble", "War Flute Sound", "Vitality Bubble", "Warrior’s Anthem", "Tenacity"] },
  { slug: "brian", name: "Brian", rarity: "UR", faction: "Warlock", role: "Tank", image: "/images/heroes/brian.webp", summary: "A wolf-like Warlock tank whose kit blends defensive staying power with close-range threat.", unlock: "Available through rotating Daily Offer packs.", skills: ["Sharp Claw", "Throat Bite", "Lunar Howl", "Wolf Bloodline", "Tenacity"] },
  { slug: "louis", name: "Louis", rarity: "UR", faction: "Ranger", role: "Tank", image: "/images/heroes/louis.webp", summary: "A resilient Ranger tank who restrains opponents and holds the formation together.", unlock: "Introduced through Daily Offers around server day 64.", skills: ["Shackles", "Cross Whip", "Force Link", "Indomitable Spirit", "Tenacity"] },
  { slug: "shadow", name: "Shadow", rarity: "UR", faction: "Ranger", role: "Tank", image: "/images/heroes/shadow.webp", summary: "A stealth-oriented Ranger tank who uses smoke and shadow attacks to survive and disrupt.", unlock: "Initially available through packs, with Tavern availability later in server progression.", skills: ["Smoke Cartridge", "Shadow Hunt", "Shadow Strike", "Shadow Veil", "Tenacity"] },
  { slug: "daskal", name: "Daskal", rarity: "UR", faction: "Warrior", role: "Tank", image: "/images/heroes/daskal.webp", summary: "A battle-hardened Warrior tank designed to endure punishment and answer with deadly counters.", unlock: "Introduced around server day 29.", skills: ["Battle Will", "Bloodshed Defense", "Deadly Pierce", "Resolute Fight", "Tenacity"] },
];

export function getHero(slug: string) { return heroes.find((hero) => hero.slug === slug); }
