-- Complete community backend: invitations, administration, moderation,
-- notifications, community chat, fan art, reports, blocks, and rate limits.

-- Platform owners are separate from in-game alliance leadership.
create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
insert into public.platform_admins (user_id)
select id from auth.users where lower(email) = 'jjames422@me.com'
on conflict (user_id) do nothing;
alter table public.platform_admins enable row level security;
revoke all on public.platform_admins from anon, authenticated;

create or replace function public.is_platform_admin()
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists (select 1 from public.platform_admins where user_id = auth.uid());
$$;
revoke execute on function public.is_platform_admin() from public;
grant execute on function public.is_platform_admin() to anon, authenticated;

create or replace function public.can_manage_alliance(p_alliance text)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select public.is_platform_admin() or exists (
    select 1 from public.alliance_members
    where user_id = auth.uid() and alliance = p_alliance
      and permission_role in ('officer', 'admin')
  );
$$;
revoke execute on function public.can_manage_alliance(text) from public, anon;
grant execute on function public.can_manage_alliance(text) to authenticated;

-- Immutable administrative audit trail.
create table if not exists public.audit_events (
  id bigint generated always as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  alliance text references public.alliances(slug) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_events_alliance_created_idx
  on public.audit_events (alliance, created_at desc);
alter table public.audit_events enable row level security;
grant select on public.audit_events to authenticated;
create policy "alliance administrators read audit events"
on public.audit_events for select to authenticated
using (public.is_platform_admin() or public.my_role(alliance) = 'admin');

-- Invitations are addressed to an existing magic-link profile. Officers may
-- invite R1-R3; alliance admins may also assign R4/R5 and unique titles.
create table if not exists public.alliance_invitations (
  id uuid primary key default gen_random_uuid(),
  alliance text not null references public.alliances(slug) on delete cascade,
  invitee_id uuid not null references public.profiles(id) on delete cascade,
  invited_by uuid not null references auth.users(id) on delete cascade,
  game_rank game_rank not null default 'r1',
  alliance_title alliance_title,
  permission_role permission_role not null default 'member',
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'revoked', 'expired')),
  expires_at timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  check (
    (game_rank in ('r1','r2','r3') and alliance_title is null)
    or (game_rank = 'r4' and (alliance_title is null or alliance_title in ('diplomat','recruiter','goddess','god_of_war')))
    or (game_rank = 'r5' and alliance_title = 'alliance_leader')
  )
);
create unique index if not exists alliance_invitations_one_pending_per_user
  on public.alliance_invitations(invitee_id) where status = 'pending';
create index if not exists alliance_invitations_alliance_idx
  on public.alliance_invitations(alliance, created_at desc);
alter table public.alliance_invitations enable row level security;
grant select on public.alliance_invitations to authenticated;
create policy "users and alliance managers read invitations"
on public.alliance_invitations for select to authenticated
using (invitee_id = auth.uid() or public.can_manage_alliance(alliance));

-- Site notifications are generated by trusted functions, never client inserts.
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 500),
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_created_idx
  on public.notifications(user_id, created_at desc);
alter table public.notifications enable row level security;
grant select, update on public.notifications to authenticated;
create policy "users read their notifications" on public.notifications
for select to authenticated using (user_id = auth.uid());
revoke update on public.notifications from authenticated;

create or replace function public.mark_notification_read(p_notification_id uuid)
returns void language sql security definer set search_path=public,pg_temp as $$
  update public.notifications set read_at=coalesce(read_at,now())
  where id=p_notification_id and user_id=auth.uid();
$$;
grant execute on function public.mark_notification_read(uuid) to authenticated;

create or replace function public.create_alliance(p_slug text,p_code text,p_name text,p_kingdom_number integer)
returns public.alliances language plpgsql security definer set search_path=public,pg_temp as $$
declare result public.alliances;
begin
  if not public.is_platform_admin() then raise exception 'Platform administrator required'; end if;
  if trim(p_slug) !~ '^[a-z0-9-]{2,40}$' then raise exception 'Invalid alliance slug'; end if;
  if upper(trim(p_code)) !~ '^[A-Z0-9]{3}$' then raise exception 'Alliance code must be three letters or numbers'; end if;
  if char_length(trim(p_name)) not between 2 and 80 then raise exception 'Invalid alliance name'; end if;
  insert into public.alliances(slug,code,name,kingdom_number)
  values(trim(p_slug),upper(trim(p_code)),trim(p_name),p_kingdom_number) returning * into result;
  insert into public.audit_events(actor_id,alliance,action,target_type,target_id)
  values(auth.uid(),result.slug,'alliance.created','alliance',result.slug);
  return result;
end;
$$;
grant execute on function public.create_alliance(text,text,text,integer) to authenticated;

create or replace function public.find_profiles_for_invite(p_query text)
returns table (id uuid, in_game_name text)
language sql stable security definer set search_path = public, pg_temp as $$
  select p.id, p.in_game_name from public.profiles p
  where auth.uid() is not null
    and char_length(trim(p_query)) >= 2
    and p.in_game_name ilike '%' || trim(p_query) || '%'
    and not exists (select 1 from public.alliance_members m where m.user_id = p.id)
  order by p.in_game_name limit 20;
$$;
grant execute on function public.find_profiles_for_invite(text) to authenticated;

create or replace function public.invite_to_alliance(
  p_alliance text, p_invitee_id uuid, p_game_rank game_rank default 'r1',
  p_alliance_title alliance_title default null,
  p_permission_role permission_role default 'member'
) returns public.alliance_invitations
language plpgsql security definer set search_path = public, pg_temp as $$
declare result public.alliance_invitations;
declare actor_role permission_role;
begin
  if not public.can_manage_alliance(p_alliance) then raise exception 'Alliance manager required'; end if;
  select public.my_role(p_alliance) into actor_role;
  if not public.is_platform_admin() and actor_role = 'officer'
     and (p_game_rank in ('r4','r5') or p_permission_role <> 'member' or p_alliance_title is not null)
  then raise exception 'Only an alliance administrator may grant officer or leader standing'; end if;
  if p_invitee_id = auth.uid() then raise exception 'You cannot invite yourself'; end if;
  if exists (select 1 from public.alliance_members where user_id = p_invitee_id)
  then raise exception 'This player already belongs to an alliance'; end if;
  update public.alliance_invitations set status = 'expired', responded_at = now()
    where invitee_id = p_invitee_id and status = 'pending' and expires_at <= now();
  insert into public.alliance_invitations
    (alliance, invitee_id, invited_by, game_rank, alliance_title, permission_role)
  values (p_alliance, p_invitee_id, auth.uid(), p_game_rank, p_alliance_title, p_permission_role)
  returning * into result;
  insert into public.notifications(user_id, kind, title, body, data)
  select p_invitee_id, 'alliance_invitation', 'Alliance invitation',
    'You were invited to join ' || a.name || '.', jsonb_build_object('invitation_id', result.id)
  from public.alliances a where a.slug = p_alliance;
  insert into public.audit_events(actor_id, alliance, action, target_type, target_id, details)
  values (auth.uid(), p_alliance, 'invitation.created', 'profile', p_invitee_id::text,
    jsonb_build_object('rank', p_game_rank, 'title', p_alliance_title, 'role', p_permission_role));
  return result;
end;
$$;
grant execute on function public.invite_to_alliance(text,uuid,game_rank,alliance_title,permission_role) to authenticated;

create or replace function public.respond_to_alliance_invitation(p_invitation_id uuid, p_accept boolean)
returns public.alliance_invitations
language plpgsql security definer set search_path = public, pg_temp as $$
declare invitation public.alliance_invitations;
begin
  select * into invitation from public.alliance_invitations
    where id = p_invitation_id and invitee_id = auth.uid() and status = 'pending' for update;
  if not found then raise exception 'Pending invitation not found'; end if;
  if invitation.expires_at <= now() then
    update public.alliance_invitations set status = 'expired', responded_at = now() where id = invitation.id
    returning * into invitation;
    return invitation;
  end if;
  if p_accept then
    insert into public.alliance_members
      (alliance,user_id,permission_role,game_rank,alliance_title,verified_at,verified_by)
    values (invitation.alliance,auth.uid(),invitation.permission_role,invitation.game_rank,
      invitation.alliance_title,now(),invitation.invited_by);
    update public.profiles set alliance = invitation.alliance,
      permission_role = invitation.permission_role where id = auth.uid();
  end if;
  update public.alliance_invitations set status = case when p_accept then 'accepted' else 'declined' end,
    responded_at = now() where id = invitation.id returning * into invitation;
  insert into public.notifications(user_id,kind,title,body,data)
  values (invitation.invited_by,'invitation_response','Invitation response',
    case when p_accept then 'Your alliance invitation was accepted.' else 'Your alliance invitation was declined.' end,
    jsonb_build_object('invitation_id', invitation.id));
  insert into public.audit_events(actor_id,alliance,action,target_type,target_id)
  values (auth.uid(),invitation.alliance,case when p_accept then 'invitation.accepted' else 'invitation.declined' end,
    'profile',auth.uid()::text);
  return invitation;
end;
$$;
grant execute on function public.respond_to_alliance_invitation(uuid,boolean) to authenticated;

create or replace function public.revoke_alliance_invitation(p_invitation_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare invitation public.alliance_invitations;
begin
  select * into invitation from public.alliance_invitations where id = p_invitation_id and status = 'pending' for update;
  if not found then raise exception 'Pending invitation not found'; end if;
  if not public.can_manage_alliance(invitation.alliance) then raise exception 'Alliance manager required'; end if;
  update public.alliance_invitations set status = 'revoked', responded_at = now() where id = invitation.id;
  insert into public.audit_events(actor_id,alliance,action,target_type,target_id)
  values (auth.uid(),invitation.alliance,'invitation.revoked','invitation',invitation.id::text);
end;
$$;
grant execute on function public.revoke_alliance_invitation(uuid) to authenticated;

create or replace function public.manage_alliance_member(
  p_user_id uuid, p_game_rank game_rank, p_alliance_title alliance_title,
  p_permission_role permission_role
) returns public.alliance_members
language plpgsql security definer set search_path = public, pg_temp as $$
declare member public.alliance_members;
begin
  select * into member from public.alliance_members where user_id = p_user_id for update;
  if not found then raise exception 'Alliance member not found'; end if;
  if not (public.is_platform_admin() or public.my_role(member.alliance) = 'admin')
  then raise exception 'Alliance administrator required'; end if;
  if p_user_id = auth.uid() and (p_permission_role <> member.permission_role or p_game_rank <> member.game_rank)
  then raise exception 'Administrators cannot change their own authority'; end if;
  update public.alliance_members set game_rank=p_game_rank, alliance_title=p_alliance_title,
    permission_role=p_permission_role, verified_at=now(), verified_by=auth.uid()
    where user_id=p_user_id returning * into member;
  update public.profiles set permission_role=p_permission_role where id=p_user_id;
  insert into public.audit_events(actor_id,alliance,action,target_type,target_id,details)
  values (auth.uid(),member.alliance,'membership.updated','profile',p_user_id::text,
    jsonb_build_object('rank',p_game_rank,'title',p_alliance_title,'role',p_permission_role));
  insert into public.notifications(user_id,kind,title,body,data)
  values (p_user_id,'membership_updated','Alliance standing updated','Your alliance rank or access was changed.',
    jsonb_build_object('alliance',member.alliance));
  return member;
end;
$$;
grant execute on function public.manage_alliance_member(uuid,game_rank,alliance_title,permission_role) to authenticated;

create or replace function public.transfer_alliance_leadership(p_new_leader_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare old_leader public.alliance_members; declare new_leader public.alliance_members;
begin
  select * into old_leader from public.alliance_members where user_id=auth.uid() and game_rank='r5' for update;
  if not found and not public.is_platform_admin() then raise exception 'Alliance leader required'; end if;
  if public.is_platform_admin() and old_leader.user_id is null then
    select * into new_leader from public.alliance_members where user_id=p_new_leader_id for update;
    select * into old_leader from public.alliance_members where alliance=new_leader.alliance and game_rank='r5' for update;
  else
    select * into new_leader from public.alliance_members
      where user_id=p_new_leader_id and alliance=old_leader.alliance for update;
  end if;
  if new_leader.user_id is null then raise exception 'New leader must belong to the alliance'; end if;
  update public.alliance_members set game_rank='r4',alliance_title=null,permission_role='officer',
    verified_at=now(),verified_by=auth.uid() where user_id=old_leader.user_id;
  update public.alliance_members set game_rank='r5',alliance_title='alliance_leader',permission_role='admin',
    verified_at=now(),verified_by=auth.uid() where user_id=new_leader.user_id;
  update public.profiles set permission_role='officer' where id=old_leader.user_id;
  update public.profiles set permission_role='admin' where id=new_leader.user_id;
  insert into public.audit_events(actor_id,alliance,action,target_type,target_id,details)
  values(auth.uid(),new_leader.alliance,'leadership.transferred','profile',new_leader.user_id::text,
    jsonb_build_object('previous_leader',old_leader.user_id));
end;
$$;
grant execute on function public.transfer_alliance_leadership(uuid) to authenticated;

create or replace function public.remove_alliance_member(p_user_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare member public.alliance_members;
begin
  select * into member from public.alliance_members where user_id=p_user_id for update;
  if not found then raise exception 'Alliance member not found'; end if;
  if not (public.is_platform_admin() or public.my_role(member.alliance)='admin')
  then raise exception 'Alliance administrator required'; end if;
  if member.game_rank='r5' then raise exception 'Transfer alliance leadership before removing the leader'; end if;
  delete from public.alliance_members where user_id=p_user_id;
  update public.profiles set alliance=null, permission_role='member' where id=p_user_id;
  insert into public.notifications(user_id,kind,title,body,data)
  values (p_user_id,'membership_removed','Alliance membership ended','You are no longer a member of the alliance.',
    jsonb_build_object('alliance',member.alliance));
  insert into public.audit_events(actor_id,alliance,action,target_type,target_id)
  values (auth.uid(),member.alliance,'membership.removed','profile',p_user_id::text);
end;
$$;
grant execute on function public.remove_alliance_member(uuid) to authenticated;

-- User blocking. Filters below hide blocked authors in comments and chat.
create table if not exists public.user_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(blocker_id,blocked_id), check (blocker_id <> blocked_id)
);
alter table public.user_blocks enable row level security;
grant select,insert,delete on public.user_blocks to authenticated;
create policy "users manage their blocks" on public.user_blocks for all to authenticated
using (blocker_id=auth.uid()) with check (blocker_id=auth.uid());

create or replace function public.is_blocked_pair(p_other uuid)
returns boolean language sql stable security definer set search_path=public,pg_temp as $$
  select exists(select 1 from public.user_blocks
    where (blocker_id=auth.uid() and blocked_id=p_other)
       or (blocker_id=p_other and blocked_id=auth.uid()));
$$;
revoke execute on function public.is_blocked_pair(uuid) from public,anon;
grant execute on function public.is_blocked_pair(uuid) to authenticated;

-- Community channels coexist with private alliance channels.
alter table public.channels add column if not exists scope text not null default 'alliance';
alter table public.channels alter column alliance drop not null;
alter table public.channels drop constraint if exists channels_scope_check;
alter table public.channels add constraint channels_scope_check check (
  (scope='alliance' and alliance is not null) or (scope='community' and alliance is null)
);
create unique index if not exists channels_one_community_slug
  on public.channels(slug) where scope='community';
insert into public.channels(alliance,slug,name,topic,min_role,sort_order,scope) values
  (null,'community-general','Community General','All Last Asylum players','member',0,'community'),
  (null,'community-help','Game Help','Questions, guides, and answers','member',1,'community'),
  (null,'fan-art','Fan Art','Share community creations','member',2,'community')
on conflict do nothing;
drop policy if exists "members see channels they're allowed in" on public.channels;
create policy "users see accessible channels" on public.channels for select to authenticated using (
  (scope='community' and exists(select 1 from public.profiles p where p.id=auth.uid()))
  or (scope='alliance' and public.role_rank(public.my_role(alliance)) >= public.role_rank(min_role))
);
drop policy if exists "members read messages in channels they can access" on public.messages;
create policy "users read accessible messages" on public.messages for select to authenticated using (
  deleted_at is null and not public.is_blocked_pair(author_id) and exists(
    select 1 from public.channels c where c.id=messages.channel_id and (
      (c.scope='community' and exists(select 1 from public.profiles p where p.id=auth.uid()))
      or (c.scope='alliance' and public.role_rank(public.my_role(c.alliance)) >= public.role_rank(c.min_role))
    )
  )
);
drop policy if exists "members post in channels they can access" on public.messages;
create policy "users post in accessible channels" on public.messages for insert to authenticated with check (
  author_id=auth.uid() and exists(
    select 1 from public.channels c where c.id=messages.channel_id and (
      (c.scope='community' and exists(select 1 from public.profiles p where p.id=auth.uid()))
      or (c.scope='alliance' and public.role_rank(public.my_role(c.alliance)) >= public.role_rank(c.min_role))
    )
  )
);

-- Private fan-art objects are downloadable only after their record is approved.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('fan-art','fan-art',false,10485760,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=false,file_size_limit=10485760,
  allowed_mime_types=excluded.allowed_mime_types;
create table if not exists public.fan_art (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  title text not null check(char_length(trim(title)) between 1 and 100),
  caption text check(char_length(caption)<=1000),
  status text not null default 'pending' check(status in ('pending','approved','rejected')),
  moderation_note text,
  moderated_by uuid references auth.users(id) on delete set null,
  moderated_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.fan_art enable row level security;
grant select,insert,delete on public.fan_art to authenticated;
grant select on public.fan_art to anon;
create policy "approved fan art is public" on public.fan_art for select to public
using(status='approved' or author_id=auth.uid() or public.is_platform_admin());
create policy "users submit their own fan art" on public.fan_art for insert to authenticated
with check(author_id=auth.uid() and status='pending' and storage_path like auth.uid()::text || '/%');
create policy "users withdraw pending fan art" on public.fan_art for delete to authenticated
using(author_id=auth.uid() and status='pending');
create policy "users upload fan art" on storage.objects for insert to authenticated
with check(bucket_id='fan-art' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "approved fan art objects are readable" on storage.objects for select to public
using(bucket_id='fan-art' and exists(select 1 from public.fan_art f where f.storage_path=name and
  (f.status='approved' or f.author_id=auth.uid() or public.is_platform_admin())));
create policy "users remove pending fan art objects" on storage.objects for delete to authenticated
using(bucket_id='fan-art' and (storage.foldername(name))[1]=auth.uid()::text and
  not exists(select 1 from public.fan_art f where f.storage_path=name and f.status='approved'));

-- Reports cover comments, messages, and fan art without granting reporters access to moderation.
create table if not exists public.content_reports (
  id uuid primary key default gen_random_uuid(), reporter_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check(target_type in ('comment','message','fan_art')),
  target_id uuid not null, reason text not null check(char_length(trim(reason)) between 3 and 500),
  status text not null default 'open' check(status in ('open','resolved','dismissed')),
  resolved_by uuid references auth.users(id) on delete set null, resolved_at timestamptz,
  created_at timestamptz not null default now(), unique(reporter_id,target_type,target_id)
);
alter table public.content_reports enable row level security;
grant select,insert on public.content_reports to authenticated;
create policy "users create and read own reports" on public.content_reports for select to authenticated
using(reporter_id=auth.uid() or public.is_platform_admin());
create policy "users create reports" on public.content_reports for insert to authenticated
with check(reporter_id=auth.uid() and status='open');

create or replace function public.moderate_content(
  p_target_type text,p_target_id uuid,p_action text,p_note text default null
) returns void language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if not public.is_platform_admin() then raise exception 'Platform administrator required'; end if;
  if p_target_type='comment' then
    update public.comments set status=case when p_action='approve' then 'approved' else 'rejected' end where id=p_target_id;
  elsif p_target_type='message' then
    update public.messages set deleted_at=case when p_action='approve' then null else now() end where id=p_target_id;
  elsif p_target_type='fan_art' then
    update public.fan_art set status=case when p_action='approve' then 'approved' else 'rejected' end,
      moderation_note=p_note,moderated_by=auth.uid(),moderated_at=now() where id=p_target_id;
  else raise exception 'Unsupported target type'; end if;
  if not found then raise exception 'Content not found'; end if;
  update public.content_reports set status='resolved',resolved_by=auth.uid(),resolved_at=now()
    where target_type=p_target_type and target_id=p_target_id and status='open';
  insert into public.audit_events(actor_id,action,target_type,target_id,details)
  values(auth.uid(),'moderation.'||p_action,p_target_type,p_target_id::text,jsonb_build_object('note',p_note));
end;
$$;
grant execute on function public.moderate_content(text,uuid,text,text) to authenticated;

-- Transactional database rate limits. Failed attempts roll back with the action.
create table if not exists public.interaction_events (
  id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,created_at timestamptz not null default now()
);
create index if not exists interaction_events_lookup_idx on public.interaction_events(user_id,action,created_at desc);
alter table public.interaction_events enable row level security;
revoke all on public.interaction_events from anon,authenticated;
create or replace function public.enforce_interaction_rate()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare action_name text:=tg_argv[0]; declare maximum int:=tg_argv[1]::int;
declare window_size interval:=tg_argv[2]::interval;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if (select count(*) from public.interaction_events where user_id=auth.uid() and action=action_name
      and created_at>now()-window_size)>=maximum then raise exception 'Rate limit exceeded'; end if;
  insert into public.interaction_events(user_id,action) values(auth.uid(),action_name);
  return new;
end;
$$;
drop trigger if exists comments_rate_limit on public.comments;
create trigger comments_rate_limit before insert on public.comments for each row execute function public.enforce_interaction_rate('comment','5','1 minute');
drop trigger if exists messages_rate_limit on public.messages;
create trigger messages_rate_limit before insert on public.messages for each row execute function public.enforce_interaction_rate('message','30','1 minute');
drop trigger if exists reactions_rate_limit on public.guide_reactions;
create trigger reactions_rate_limit before insert on public.guide_reactions for each row execute function public.enforce_interaction_rate('reaction','30','1 minute');
drop trigger if exists fan_art_rate_limit on public.fan_art;
create trigger fan_art_rate_limit before insert on public.fan_art for each row execute function public.enforce_interaction_rate('fan_art','5','1 day');
drop trigger if exists reports_rate_limit on public.content_reports;
create trigger reports_rate_limit before insert on public.content_reports for each row execute function public.enforce_interaction_rate('report','10','1 hour');

-- Approved comments remain public, but authenticated users do not see either side of a block.
create or replace function public.get_guide_comments(p_alliance text,p_guide_slug text)
returns table(id uuid,body text,identity_label text,created_at timestamptz)
language sql stable security definer set search_path=public,pg_temp as $$
  select c.id,c.body,
    case when c.author_id is null then c.author_name || case when c.author_rank is null then '' else ' · '||c.author_rank end
         else coalesce(public.format_member_identity(c.author_id),'Former member') end,c.created_at
  from public.comments c where c.status='approved' and c.alliance=p_alliance and c.guide_slug=p_guide_slug
    and (auth.uid() is null or c.author_id is null or not public.is_blocked_pair(c.author_id))
  order by c.created_at desc;
$$;

-- Small health contract for deploy checks; no user data is exposed.
create or replace function public.backend_health()
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
  select jsonb_build_object(
    'status','ok','alliance_count',(select count(*) from public.alliances),
    'pending_invitations',(select count(*) from public.alliance_invitations where status='pending' and expires_at>now()),
    'open_reports',(select count(*) from public.content_reports where status='open'),
    'checked_at',now()
  ) where public.is_platform_admin();
$$;
revoke execute on function public.backend_health() from public,anon;
grant execute on function public.backend_health() to authenticated;

-- Direct writes to authority-bearing tables stay closed; only RPCs above mutate them.
revoke insert,update,delete on public.alliance_members from anon,authenticated;
revoke insert,update,delete on public.alliance_invitations from anon,authenticated;
revoke insert,update,delete on public.audit_events from anon,authenticated;
